"""The API/UI receipt fixture is generated by the same projection used at runtime."""
import json
from itertools import permutations
from pathlib import Path

import pytest

from app.modules.access_devices.base import gate_receipt_projection
from app.modules.gate.base import CommandDelivery, GateCommandDelivery


def test_gate_receipt_fixture_matches_runtime_projection():
    fixture = json.loads((Path(__file__).parent / "fixtures/gates/command_receipts.json").read_text())
    assert fixture["contract_version"] == 1
    for case in fixture["cases"]:
        actual = gate_receipt_projection(case["outcome"]["target_receipts"],
            admission_target_device_id=case["admission_target_device_id"],
            expected_target_count=case["expected_target_count"])
        assert actual == case["outcome"], case["name"]


def test_gate_aggregate_receipt_is_order_independent_including_partial_delivery():
    fixture = json.loads((Path(__file__).parent / "fixtures/gates/command_receipts.json").read_text())
    for case in fixture["cases"]:
        expected = {key: value for key, value in case["outcome"].items() if key != "target_receipts"}
        for ordered in permutations(case["outcome"]["target_receipts"]):
            result = gate_receipt_projection(list(ordered), admission_target_device_id=case["admission_target_device_id"],
                                             expected_target_count=case["expected_target_count"])
            assert {key: value for key, value in result.items() if key != "target_receipts"} == expected, case["name"]


def test_partial_is_an_aggregate_outcome_not_a_provider_receipt():
    assert GateCommandDelivery("partial") == GateCommandDelivery.PARTIAL
    with pytest.raises(ValueError):
        CommandDelivery("partial")


def test_incomplete_aggregate_cannot_claim_no_target_was_sent():
    receipt = {"target_device_id": "entry", "accepted": True, "delivery": "accepted", "state": "open",
               "verified": True, "requires_reconciliation": False}
    result = gate_receipt_projection([receipt], admission_target_device_id="entry", expected_target_count=2)
    assert result["delivery"] == "unknown" and result["requires_reconciliation"] is True
    assert result["admission_verified"] is True


def test_frontend_receipt_fixture_is_exact_canonical_copy():
    repo = Path(__file__).resolve().parents[3]
    canonical = Path(__file__).parent / "fixtures/gates/command_receipts.json"
    frontend = repo / "frontend/src/api/fixtures/gateCommandReceipts.generated.json"
    assert frontend.read_bytes() == canonical.read_bytes()


def test_frontend_receipt_page_fixture_is_exact_canonical_copy():
    repo = Path(__file__).resolve().parents[3]
    canonical = Path(__file__).parent / "fixtures/gates/receipt_pages.json"
    frontend = repo / "frontend/src/api/fixtures/gateReceiptPages.generated.json"
    assert frontend.read_bytes() == canonical.read_bytes()
